apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.port }}  # The port exposed by the service
      targetPort: {{ .Values.port }}  # The port the container listens on
  type: LoadBalancer  # Optionally use LoadBalancer if you need an external IP

